# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [develop]
    paths:
      - "${some_project}/**"
  pull_request:
    branches: [develop]
    paths:
      - "${some_project}/**"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_PROJECT: "some_project"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ${DJANGO_PROJECT}/requirements_ci.txt ]; then pip install -r ${DJANGO_PROJECT}/requirements_ci.txt; fi
      - name: Lint with flake8
        run: |
          cd ${DJANGO_PROJECT}
          flake8 ${DJANGO_PROJECT} --count
      - name: Test with pytest
        run: |
          pytest
