# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [develop]
    paths:
      - "some_project/**"
  pull_request:
    branches: [develop]
    paths:
      - "some_project/**"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_PROJECT: "some_project"
      PYTHON_REQUIREMENTS_FILE: "requirements_ci.txt"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # 依存関係のキャッシングによるワークフロー高速化
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ./${DJANGO_PROJECT}/${PYTHON_REQUIREMENTS_FILE} ]; then pip install -r ./${DJANGO_PROJECT}/${PYTHON_REQUIREMENTS_FILE}; fi
      - name: Check Format with black
        working-directory: ./${{ env.DJANGO_PROJECT }}
        # black targets
        # --include (\.pyi?|\.ipynb)$
        # --exclude /(\.direnv|\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|venv|\.svn|_build|buck-out|build|dist)/
        run: |
          black --check .
      - name: Lint with flake8
        working-directory: ./${{ env.DJANGO_PROJECT }}
        run: |
          flake8 . --count
      - name: Run isort
        working-directory: ./${{ env.DJANGO_PROJECT }}
        run: |
          isort **/*.py -c -v
      - name: Test with pytest
        working-directory: ./${{ env.DJANGO_PROJECT }}
        # migrations, migrate は migrateファイルをリポジトリに配置後は不要なので削除
        run: |
          python manage.py makemigrations
          python manage.py migrate
          pytest
